/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRidesRouteImport } from './routes/_authenticated/rides'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedRidesNewRouteImport } from './routes/_authenticated/rides.new'
import { Route as AuthenticatedRidesRideIdRouteImport } from './routes/_authenticated/rides.$rideId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminRidesRouteImport } from './routes/_authenticated/admin/rides'
import { Route as AuthenticatedAdminRefundsRouteImport } from './routes/_authenticated/admin/refunds'
import { Route as AuthenticatedAdminDriversRouteImport } from './routes/_authenticated/admin/drivers'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRidesRoute = AuthenticatedRidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedRidesNewRoute = AuthenticatedRidesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRidesRoute,
} as any)
const AuthenticatedRidesRideIdRoute =
  AuthenticatedRidesRideIdRouteImport.update({
    id: '/$rideId',
    path: '/$rideId',
    getParentRoute: () => AuthenticatedRidesRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRidesRoute = AuthenticatedAdminRidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRefundsRoute =
  AuthenticatedAdminRefundsRouteImport.update({
    id: '/refunds',
    path: '/refunds',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDriversRoute =
  AuthenticatedAdminDriversRouteImport.update({
    id: '/drivers',
    path: '/drivers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rides': typeof AuthenticatedRidesRouteWithChildren
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/admin/rides': typeof AuthenticatedAdminRidesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/rides/$rideId': typeof AuthenticatedRidesRideIdRoute
  '/rides/new': typeof AuthenticatedRidesNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rides': typeof AuthenticatedRidesRouteWithChildren
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/admin/rides': typeof AuthenticatedAdminRidesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/rides/$rideId': typeof AuthenticatedRidesRideIdRoute
  '/rides/new': typeof AuthenticatedRidesNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/rides': typeof AuthenticatedRidesRouteWithChildren
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/_authenticated/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/_authenticated/admin/rides': typeof AuthenticatedAdminRidesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/rides/$rideId': typeof AuthenticatedRidesRideIdRoute
  '/_authenticated/rides/new': typeof AuthenticatedRidesNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/history'
    | '/profile'
    | '/rides'
    | '/admin/analytics'
    | '/admin/drivers'
    | '/admin/refunds'
    | '/admin/rides'
    | '/admin/users'
    | '/rides/$rideId'
    | '/rides/new'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/history'
    | '/profile'
    | '/rides'
    | '/admin/analytics'
    | '/admin/drivers'
    | '/admin/refunds'
    | '/admin/rides'
    | '/admin/users'
    | '/rides/$rideId'
    | '/rides/new'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/history'
    | '/_authenticated/profile'
    | '/_authenticated/rides'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/drivers'
    | '/_authenticated/admin/refunds'
    | '/_authenticated/admin/rides'
    | '/_authenticated/admin/users'
    | '/_authenticated/rides/$rideId'
    | '/_authenticated/rides/new'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rides': {
      id: '/_authenticated/rides'
      path: '/rides'
      fullPath: '/rides'
      preLoaderRoute: typeof AuthenticatedRidesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/rides/new': {
      id: '/_authenticated/rides/new'
      path: '/new'
      fullPath: '/rides/new'
      preLoaderRoute: typeof AuthenticatedRidesNewRouteImport
      parentRoute: typeof AuthenticatedRidesRoute
    }
    '/_authenticated/rides/$rideId': {
      id: '/_authenticated/rides/$rideId'
      path: '/$rideId'
      fullPath: '/rides/$rideId'
      preLoaderRoute: typeof AuthenticatedRidesRideIdRouteImport
      parentRoute: typeof AuthenticatedRidesRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rides': {
      id: '/_authenticated/admin/rides'
      path: '/rides'
      fullPath: '/admin/rides'
      preLoaderRoute: typeof AuthenticatedAdminRidesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/refunds': {
      id: '/_authenticated/admin/refunds'
      path: '/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AuthenticatedAdminRefundsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/drivers': {
      id: '/_authenticated/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AuthenticatedAdminDriversRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminDriversRoute: typeof AuthenticatedAdminDriversRoute
  AuthenticatedAdminRefundsRoute: typeof AuthenticatedAdminRefundsRoute
  AuthenticatedAdminRidesRoute: typeof AuthenticatedAdminRidesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminDriversRoute: AuthenticatedAdminDriversRoute,
  AuthenticatedAdminRefundsRoute: AuthenticatedAdminRefundsRoute,
  AuthenticatedAdminRidesRoute: AuthenticatedAdminRidesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRidesRouteChildren {
  AuthenticatedRidesRideIdRoute: typeof AuthenticatedRidesRideIdRoute
  AuthenticatedRidesNewRoute: typeof AuthenticatedRidesNewRoute
}

const AuthenticatedRidesRouteChildren: AuthenticatedRidesRouteChildren = {
  AuthenticatedRidesRideIdRoute: AuthenticatedRidesRideIdRoute,
  AuthenticatedRidesNewRoute: AuthenticatedRidesNewRoute,
}

const AuthenticatedRidesRouteWithChildren =
  AuthenticatedRidesRoute._addFileChildren(AuthenticatedRidesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRidesRoute: typeof AuthenticatedRidesRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRidesRoute: AuthenticatedRidesRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
