// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient(): ReturnType<typeof createClient<Database>> {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const runtimeEnv = typeof process !== 'undefined' ? process.env : {};
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    runtimeEnv.SUPABASE_URL ||
    runtimeEnv.VITE_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    runtimeEnv.SUPABASE_PUBLISHABLE_KEY ||
    runtimeEnv.SUPABASE_ANON_KEY ||
    runtimeEnv.VITE_SUPABASE_PUBLISHABLE_KEY ||
    runtimeEnv.VITE_SUPABASE_ANON_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing: string[] = [];
    if (!SUPABASE_URL) missing.push('VITE_SUPABASE_URL');
    if (!SUPABASE_PUBLISHABLE_KEY) missing.push('VITE_SUPABASE_ANON_KEY');
    console.warn(`[Supabase] Missing: ${missing.join(', ')}. Add them as Vercel Environment Variables.`);
    return createNoopClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

/** Returns a Proxy that safely handles the Supabase API patterns used in this codebase,
 * returning null/empty results so the app renders public pages without env vars. */
function createNoopClient(): ReturnType<typeof createClient<Database>> {
  const emptyResult = { data: null, error: null, count: null };
  const emptyArrayResult = { data: [], error: null, count: null };
  const emptySessionResult = { data: { session: null, user: null }, error: null };
  const noopSub = { subscription: { unsubscribe: () => {} } };

  const buildHandler = (isTopLevel = false) => ({
    get(_target: any, prop: string) {
      if (prop === 'then') return undefined; // not a Promise
      if (prop === 'toPromise') return () => Promise.resolve(emptyResult);
      if (isTopLevel) {
        if (prop === 'auth') return new Proxy({}, {
          get(_t: any, p: string) {
            if (p === 'getSession') return () => Promise.resolve(emptySessionResult);
            if (p === 'getUser') return () => Promise.resolve(emptySessionResult);
            if (p === 'onAuthStateChange') return () => noopSub;
            return () => Promise.resolve(emptyResult);
          },
        });
        if (prop === 'from') return () => new Proxy({}, {
          get(_t: any, p: string) {
            if (p === 'select' || p === 'update' || p === 'insert' || p === 'delete') {
              return () => new Proxy({}, {
                get(_x: any, q: string) {
                  if (q === 'eq' || q === 'neq' || q === 'gt' || q === 'gte' || q === 'lt' || q === 'lte' || q === 'like' || q === 'ilike' || q === 'in' || q === 'is' || q === 'order' || q === 'limit' || q === 'range') {
                    return () => new Proxy({}, { get: () => () => Promise.resolve(emptyArrayResult) });
                  }
                  if (q === 'then') return undefined;
                  return () => Promise.resolve(emptyArrayResult);
                },
              });
            }
            if (p === 'then') return undefined;
            return () => Promise.resolve(emptyArrayResult);
          },
        });
        if (prop === 'rpc') return () => Promise.resolve(emptyResult);
      }
      // For chained calls that end with a query
      return () => Promise.resolve(prop === 'select' ? emptyArrayResult : emptyResult);
    },
    apply(_target: any, _thisArg: any, _args: any[]) {
      return Promise.resolve(emptyResult);
    },
  });

  return new Proxy({} as any, buildHandler(true));
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});